### ISSUE TITLE
Issue installing Oasis LMF on Mac with Apple M1 Chip

### ISSUE THREAD

**Issue by samroeslin** [OasisLMF/OasisEvaluation#28]
## Issue Description
Hello Oasis LMF community,
I am new to Oasis and I am trying to install Oasis LMF following the YouTube tutorial "2c. Oasis LMF Installation Guide - LINUX Based OS" recorded by Sam Gamble from Oasis LMF in July 2020. 
The video is well explained and I could get over most of the steps. However, I am getting errors when it tries pulling from server-db and celery-db 

After an online search, I have seen that some people using an Apple M1 Chip and Docker experienced similar errors. They solved the issue adding "platform: linux/x86_64" to the yml.
I tried it but was not successful.

Any advice or suggestions would be welcome. Thanks.

## Version / Environment information
Oasis 1.19.0 release

macOS Big Sur Version 11.4
MacBook Air (M1, 2020)
Chip Apple M1
Memory 16 GB

## Example data / logs
Pulling server-db      ... pulling from library/mysql
Pulling celery-db      ... pulling from library/mysql
Pulling rabbit         ... done
Pulling worker         ... done
Pulling worker-monitor ... done
Pulling server         ... done
Pulling flower         ... done

ERROR: for server-db  no matching manifest for linux/arm64/v8 in the manifest list entries
ERROR: for celery-db  no matching manifest for linux/arm64/v8 in the manifest list entries
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by sambles** [comment]
Hello and thanks for the issue report, 

This looks like a problem specific to the MySQL image and its support for only `amd64`. We do have a compose file setup which runs PostgreSQL containers in place of MySQL. That has support for `arm/v6`,  `arm/v7` and `arm/v8`  
So should hopefully run without needing a work around. 

Would you be able to test [OasisPlatform/postgres.docker-compose.yml](https://github.com/OasisLMF/OasisPlatform/blob/master/postgres.docker-compose.yml) and see if the Postgre images run on M1 silicon? 
If the **server-db** / **celery-db** containers look ok i can setup a branch for running oasis with the Postgre configuration.  

## Testing Steps
1.  Download the **postgres.docker-compose.yml** file to the evaluation directory 
`$ wget https://raw.githubusercontent.com/OasisLMF/OasisPlatform/master/postgres.docker-compose.yml`

2.  Run the compose file, and check for error messages 
`$ docker-compose -f postgres.docker-compose.yml up -d`

**Comment by samroeslin** [comment]
Hi sambles,

Thanks for the help. 

With the new yml file the pulling of the data from Postgre was successful 'Pull complete'
However, I get an error with rabbit. Probably something related to docker. I need to explore further.

## Example data / logs

Example error Trace:

```
docker-compose -f postgres.docker-compose.yml up -d
WARNING: Found orphan containers (oasisui_proxy, oasisevaluation_portainer_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Pulling server-db (postgres:)...
latest: Pulling from library/postgres
513c6babab2b: Pull complete
0cfa7a321c31: Pull complete
9315b730bf6b: Pull complete
a9760a0fafc3: Pull complete
089b0b3bfd09: Pull complete
b795028cb59c: Pull complete
f211e772a681: Pull complete
5d64663d526b: Pull complete
ea82f0c79586: Pull complete
7716f8fb4edc: Pull complete
1a040b0dee24: Pull complete
72449b83a5dd: Pull complete
8efaac5888a8: Pull complete
Digest: sha256:6647385dd9ae11aa2216bf55c54d126b0a85637b3cf4039ef24e3234113588e3
Status: Downloaded newer image for postgres:latest
Pulling rabbit (rabbitmq:3-management)...
3-management: Pulling from library/rabbitmq
be0de17fe24f: Pull complete
0afa0411a278: Pull complete
41f2d2ef3bff: Pull complete
f16624c494ac: Pull complete
f1ea9d5029cf: Pull complete
4857a4935b80: Pull complete
d4cd6106bc10: Pull complete
10badd53e975: Pull complete
727fa66efe92: Pull complete
4658fc63df23: Pull complete
Digest: sha256:b29faeb169f3488b3ccfee7ac889c1c804c7102be83cb439e24bddabe5e6bdfb
Status: Downloaded newer image for rabbitmq:3-management
Building worker
[+] Building 0.0s (1/2)                                                                                                                                    
 => [internal] load build definition from Dockerfile.model_worker                                                                                     0.0s
 => => transferring dockerfile: 2B                                                                                                                    0.0s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount988581525/Dockerfile.model_worker: no such file or directory
ERROR: Service 'worker' failed to build : Build failed
```

**Comment by sambles** [comment]
Ah yes the RabbitMQ issue might be related to this https://github.com/OasisLMF/OasisPlatform/issues/515
If its the same error then pinning image version to `rabbitmq:3.8.14-management` should fix that

**Comment by samroeslin** [comment]
I have pinned image version to `rabbitmq:3.8.14-management`

When I run the updated version of `docker-compose -f postgres.docker-compose.yml up -d` I still get 

```
docker-compose -f postgres.docker-compose.yml up -d
Building worker
[+] Building 0.0s (1/2)                                                                                       
 => [internal] load build definition from Dockerfile.model_worker                                        0.0s
 => => transferring dockerfile: 2B                                                                       0.0s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount285560748/Dockerfile.model_worker: no such file or directory
```

My guess is that the issue comes from Docker but I am not really sure.

I have downloaded Docker for Apple Silicon (https://docs.docker.com/docker-for-mac/apple-silicon/).
When I try the 'docker/getting-started' tutorial from Docker I am able to launch it in the browser without issues.

**Comment by samroeslin** [comment]
Okay I think I found the possible issue.

I specified the exact version in the file postgres.docker-compose.yml 

```
  worker:
    restart: always
    image: coreoasis/model_worker:1.19.0
    build:
      context: .
      dockerfile: Dockerfile.model_worker
    links:
     - celery-db
     - rabbit:myrabbit
```

the image was set to `image: coreoasis/model_worker:latest` previously

**Comment by samroeslin** [comment]
Thought I would list the points that I followed until now maybe it is helpful for the community and someone having a Mac with Apple Silicon.
_Caveat: I was able to get access to the Oasis UI but I am still experiencing issues with the link to the jupyter notebook at localhost:8888_

So this is what I have done so far

1. Install docker, docker-compose for Mac with **Apple chip** (https://docs.docker.com/docker-for-mac/install/), and also make sure you have Git
2. Clone the repo: https://github.com/OasisLMF/OasisEvaluation
`$ git clone https://github.com/OasisLMF/OasisEvaluation.git`
3. Navigate to the folder OasisEvaluation `cd OasisEvaluation`
4. If running the original deployment script `sudo ./install.sh` you experience issues with the databases then
5. Download the postgres.docker-compose.yml file to the evaluation directory
`$ wget https://raw.githubusercontent.com/OasisLMF/OasisPlatform/master/postgres.docker-compose.yml`
(note that this require first to install brew
`$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
then install wget with brew:
`$ brew install wget`
6. In the file postgres.docker-compose.yml pin the exact version of the worker
By default:
```
	worker:
	    restart: always
	    image: coreoasis/model_worker:latest
	    build:
	      context: .
	      dockerfile: Dockerfile.model_worker
	    links:
	     - celery-db
	     - rabbit:myrabbit
```
Changed to:
```
	worker:
	    restart: always
	    image: coreoasis/model_worker:1.19.0 (replace this by the Oasis version)
	    build:
	      context: .
	      dockerfile: Dockerfile.model_worker
	    links:
	     - celery-db
	     - rabbit:myrabbit
```	
This will avoid the error related to the BuildingWorker

7. Run the file
'$ docker-compose -f postgres.docker-compose.yml up -d

```
Creating oasisevaluation_server-db_1 ... done
Creating oasisevaluation_rabbit_1    ... done
Creating oasisevaluation_celery-db_1 ... done
Creating oasisevaluation_worker-monitor_1 ... done
Creating oasisevaluation_worker_1         ... done
Creating oasisevaluation_server_1         ... done
Creating oasisevaluation_flower_1         ... done
```

8. Run the OasisUI
	`docker-compose -f oasis-ui.yml up -d`

Open the Oasis UI via the link in the notebook or via Docker Desktop clicking on "OPEN IN BROWSER" 

<img width="1271" alt="Docker_on_Mac" src="https://user-images.githubusercontent.com/30302333/129676670-193f3af3-7995-4261-b164-d084acbd66b4.png">

but I am experiencing issues with the analysis

<img width="1440" alt="Screen Shot 2021-08-17 at 7 03 34 PM" src="https://user-images.githubusercontent.com/30302333/129679486-fcfc58df-8ffa-46a7-b29d-033bd18ce3f3.png">


so I have probably made a mistake somewhere.

Make sure to check those videos, they are really helpful
[2c. Oasis LMF Installation Guide - LINUX Based OS](https://www.youtube.com/watch?v=OFLTpGGEM10&t=6s)
[2b. Oasis LMF Installation Guide - Windows 10 OS](https://www.youtube.com/watch?v=SxRt5E-Y5Sw)

**Comment by benhayes21** [comment]
Installs now - Max to test full run

**Comment by sambles** [comment]
> Note: Only works if ktools is compiled directly on M1 macs (oasislmf package)  possible fix is create per-compiled bins by using an M1 instance on AWS (currently no runners in github actions)

**Comment by benhayes21** [comment]
Document steps and limitations in README
